/**
 * Mock Courses Data
 * 5 courses per program = 25 total
 * 1 draft, 4 published per program
 */

import { mockId, PREFIXES } from './index';
import { PROGRAM_IDS } from './programs';
import { LEVEL_IDS } from './program-levels';
import { DEPT_IDS } from './departments';
import { STAFF_IDS } from './staff';

// Course IDs for reference
export const COURSE_IDS = {
  // Experiential Therapy (5 courses)
  EXP_C1: mockId(PREFIXES.COURSE, 1),
  EXP_C2: mockId(PREFIXES.COURSE, 2),
  EXP_C3: mockId(PREFIXES.COURSE, 3),
  EXP_C4: mockId(PREFIXES.COURSE, 4),
  EXP_C5: mockId(PREFIXES.COURSE, 5), // draft
  // CBT (5 courses)
  CBT_C1: mockId(PREFIXES.COURSE, 6),
  CBT_C2: mockId(PREFIXES.COURSE, 7),
  CBT_C3: mockId(PREFIXES.COURSE, 8),
  CBT_C4: mockId(PREFIXES.COURSE, 9),
  CBT_C5: mockId(PREFIXES.COURSE, 10), // draft
  // EMDR (5 courses)
  EMDR_C1: mockId(PREFIXES.COURSE, 11),
  EMDR_C2: mockId(PREFIXES.COURSE, 12),
  EMDR_C3: mockId(PREFIXES.COURSE, 13),
  EMDR_C4: mockId(PREFIXES.COURSE, 14),
  EMDR_C5: mockId(PREFIXES.COURSE, 15), // draft
  // Somatic (5 courses)
  SOM_C1: mockId(PREFIXES.COURSE, 16),
  SOM_C2: mockId(PREFIXES.COURSE, 17),
  SOM_C3: mockId(PREFIXES.COURSE, 18),
  SOM_C4: mockId(PREFIXES.COURSE, 19),
  SOM_C5: mockId(PREFIXES.COURSE, 20), // draft
  // DBT (5 courses)
  DBT_C1: mockId(PREFIXES.COURSE, 21),
  DBT_C2: mockId(PREFIXES.COURSE, 22),
  DBT_C3: mockId(PREFIXES.COURSE, 23),
  DBT_C4: mockId(PREFIXES.COURSE, 24),
  DBT_C5: mockId(PREFIXES.COURSE, 25), // draft
};

const now = new Date();

export const courses = [
  // ============ Experiential Therapy Courses ============
  {
    _id: COURSE_IDS.EXP_C1,
    title: 'Mock Attunement Basics',
    shortDescription: 'Introduction to therapeutic attunement',
    longDescription: 'Learn the fundamentals of therapeutic attunement and how to create a safe, connected therapeutic space.',
    program: PROGRAM_IDS.EXPERIENTIAL,
    programLevel: LEVEL_IDS.EXP_L1,
    department: DEPT_IDS.MET,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.WILLIAM,
    primaryInstructors: [STAFF_IDS.WILLIAM],
    secondaryInstructors: [STAFF_IDS.CHARLES],
    createdBy: STAFF_IDS.WILLIAM,
  },
  {
    _id: COURSE_IDS.EXP_C2,
    title: 'Mock Emotional Regulation 101',
    shortDescription: 'Building emotional awareness and regulation skills',
    longDescription: 'Develop skills for helping clients identify, understand, and regulate their emotional experiences.',
    program: PROGRAM_IDS.EXPERIENTIAL,
    programLevel: LEVEL_IDS.EXP_L1,
    department: DEPT_IDS.MET,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.WILLIAM,
    primaryInstructors: [STAFF_IDS.WILLIAM],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.WILLIAM,
  },
  {
    _id: COURSE_IDS.EXP_C3,
    title: 'Mock Body-Mind Connection',
    shortDescription: 'Integrating somatic awareness in therapy',
    longDescription: 'Explore the interconnection between physical sensations and emotional states in therapeutic work.',
    program: PROGRAM_IDS.EXPERIENTIAL,
    programLevel: LEVEL_IDS.EXP_L2,
    department: DEPT_IDS.MET,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.CHARLES,
    primaryInstructors: [STAFF_IDS.CHARLES],
    secondaryInstructors: [STAFF_IDS.WILLIAM],
    createdBy: STAFF_IDS.CHARLES,
  },
  {
    _id: COURSE_IDS.EXP_C4,
    title: 'Mock Advanced Attunement',
    shortDescription: 'Deep relational work and rupture repair',
    longDescription: 'Advanced techniques for maintaining attunement through therapeutic challenges and repairing relationship ruptures.',
    program: PROGRAM_IDS.EXPERIENTIAL,
    programLevel: LEVEL_IDS.EXP_L2,
    department: DEPT_IDS.MET,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.WILLIAM,
    primaryInstructors: [STAFF_IDS.WILLIAM],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.WILLIAM,
  },
  {
    _id: COURSE_IDS.EXP_C5,
    title: 'Mock Integration Techniques',
    shortDescription: 'Synthesizing experiential methods',
    longDescription: 'Learn to integrate various experiential approaches into a cohesive therapeutic framework.',
    program: PROGRAM_IDS.EXPERIENTIAL,
    programLevel: LEVEL_IDS.EXP_L2,
    department: DEPT_IDS.MET,
    status: 'draft', // Draft course
    primaryInstructors: [STAFF_IDS.CHARLES],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.CHARLES,
  },

  // ============ CBT Courses ============
  {
    _id: COURSE_IDS.CBT_C1,
    title: 'Mock CBT Foundations',
    shortDescription: 'Core concepts of cognitive behavioral therapy',
    longDescription: 'Introduction to the cognitive model and fundamental CBT principles.',
    program: PROGRAM_IDS.CBT,
    programLevel: LEVEL_IDS.CBT_L1,
    department: DEPT_IDS.MCS,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.JANE,
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [STAFF_IDS.WILLIAM],
    createdBy: STAFF_IDS.JANE,
  },
  {
    _id: COURSE_IDS.CBT_C2,
    title: 'Mock Thought Records',
    shortDescription: 'Documenting and analyzing automatic thoughts',
    longDescription: 'Master the use of thought records for identifying and examining cognitive patterns.',
    program: PROGRAM_IDS.CBT,
    programLevel: LEVEL_IDS.CBT_L1,
    department: DEPT_IDS.MCS,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.JANE,
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.JANE,
  },
  {
    _id: COURSE_IDS.CBT_C3,
    title: 'Mock Cognitive Distortions',
    shortDescription: 'Identifying thinking errors',
    longDescription: 'Learn to recognize and categorize common cognitive distortions in client thinking.',
    program: PROGRAM_IDS.CBT,
    programLevel: LEVEL_IDS.CBT_L2,
    department: DEPT_IDS.MCS,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.JANE,
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.JANE,
  },
  {
    _id: COURSE_IDS.CBT_C4,
    title: 'Mock Behavioral Experiments',
    shortDescription: 'Testing beliefs through action',
    longDescription: 'Design and implement behavioral experiments to test and modify client beliefs.',
    program: PROGRAM_IDS.CBT,
    programLevel: LEVEL_IDS.CBT_L3,
    department: DEPT_IDS.MCS,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.JANE,
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [STAFF_IDS.WILLIAM],
    createdBy: STAFF_IDS.JANE,
  },
  {
    _id: COURSE_IDS.CBT_C5,
    title: 'Mock Relapse Prevention',
    shortDescription: 'Maintaining therapeutic gains',
    longDescription: 'Strategies for helping clients maintain progress and prevent relapse.',
    program: PROGRAM_IDS.CBT,
    programLevel: LEVEL_IDS.CBT_L3,
    department: DEPT_IDS.MCS,
    status: 'draft', // Draft course
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.JANE,
  },

  // ============ EMDR Courses ============
  {
    _id: COURSE_IDS.EMDR_C1,
    title: 'Mock EMDR Protocol Basics',
    shortDescription: 'Introduction to the 8-phase protocol',
    longDescription: 'Learn the standard EMDR protocol including history taking, preparation, and assessment phases.',
    program: PROGRAM_IDS.EMDR,
    programLevel: LEVEL_IDS.EMDR_L1,
    department: DEPT_IDS.MTR,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.CHARLES,
    primaryInstructors: [STAFF_IDS.CHARLES],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.CHARLES,
  },
  {
    _id: COURSE_IDS.EMDR_C2,
    title: 'Mock Bilateral Stimulation',
    shortDescription: 'Techniques for dual attention',
    longDescription: 'Master various forms of bilateral stimulation including eye movements, tapping, and auditory methods.',
    program: PROGRAM_IDS.EMDR,
    programLevel: LEVEL_IDS.EMDR_L1,
    department: DEPT_IDS.MTR,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.CHARLES,
    primaryInstructors: [STAFF_IDS.CHARLES],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.CHARLES,
  },
  {
    _id: COURSE_IDS.EMDR_C3,
    title: 'Mock Resource Installation',
    shortDescription: 'Building client resources',
    longDescription: 'Develop skills for installing positive resources and safe place imagery.',
    program: PROGRAM_IDS.EMDR,
    programLevel: LEVEL_IDS.EMDR_L2,
    department: DEPT_IDS.MTR,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.CHARLES,
    primaryInstructors: [STAFF_IDS.CHARLES],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.CHARLES,
  },
  {
    _id: COURSE_IDS.EMDR_C4,
    title: 'Mock Complex Trauma EMDR',
    shortDescription: 'EMDR with complex presentations',
    longDescription: 'Adaptations of EMDR for complex trauma, dissociation, and attachment issues.',
    program: PROGRAM_IDS.EMDR,
    programLevel: LEVEL_IDS.EMDR_L2,
    department: DEPT_IDS.MTR,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.CHARLES,
    primaryInstructors: [STAFF_IDS.CHARLES],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.CHARLES,
  },
  {
    _id: COURSE_IDS.EMDR_C5,
    title: 'Mock EMDR Supervision',
    shortDescription: 'Consultation and case review',
    longDescription: 'Guidelines for EMDR supervision and consultation practices.',
    program: PROGRAM_IDS.EMDR,
    programLevel: LEVEL_IDS.EMDR_L2,
    department: DEPT_IDS.MTR,
    status: 'draft', // Draft course
    primaryInstructors: [STAFF_IDS.CHARLES],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.CHARLES,
  },

  // ============ Somatic Courses ============
  {
    _id: COURSE_IDS.SOM_C1,
    title: 'Mock Body Scan Techniques',
    shortDescription: 'Developing somatic awareness',
    longDescription: 'Learn to guide clients through body awareness exercises and sensation tracking.',
    program: PROGRAM_IDS.SOMATIC,
    programLevel: LEVEL_IDS.SOM_L1,
    department: DEPT_IDS.MET,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.WILLIAM,
    primaryInstructors: [STAFF_IDS.WILLIAM],
    secondaryInstructors: [STAFF_IDS.CHARLES],
    createdBy: STAFF_IDS.WILLIAM,
  },
  {
    _id: COURSE_IDS.SOM_C2,
    title: 'Mock Grounding Exercises',
    shortDescription: 'Techniques for present-moment awareness',
    longDescription: 'Somatic grounding techniques for regulation and safety.',
    program: PROGRAM_IDS.SOMATIC,
    programLevel: LEVEL_IDS.SOM_L1,
    department: DEPT_IDS.MET,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.WILLIAM,
    primaryInstructors: [STAFF_IDS.WILLIAM],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.WILLIAM,
  },
  {
    _id: COURSE_IDS.SOM_C3,
    title: 'Mock Movement in Therapy',
    shortDescription: 'Integrating movement interventions',
    longDescription: 'Using movement and gesture in therapeutic sessions.',
    program: PROGRAM_IDS.SOMATIC,
    programLevel: LEVEL_IDS.SOM_L2,
    department: DEPT_IDS.MET,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.WILLIAM,
    primaryInstructors: [STAFF_IDS.WILLIAM],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.WILLIAM,
  },
  {
    _id: COURSE_IDS.SOM_C4,
    title: 'Mock Trauma and the Body',
    shortDescription: 'Somatic trauma resolution',
    longDescription: 'Understanding how trauma is stored in the body and somatic approaches to resolution.',
    program: PROGRAM_IDS.SOMATIC,
    programLevel: LEVEL_IDS.SOM_L3,
    department: DEPT_IDS.MET,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.CHARLES,
    primaryInstructors: [STAFF_IDS.CHARLES],
    secondaryInstructors: [STAFF_IDS.WILLIAM],
    createdBy: STAFF_IDS.CHARLES,
  },
  {
    _id: COURSE_IDS.SOM_C5,
    title: 'Mock Somatic Integration',
    shortDescription: 'Advanced somatic methods',
    longDescription: 'Integrating somatic approaches with other therapeutic modalities.',
    program: PROGRAM_IDS.SOMATIC,
    programLevel: LEVEL_IDS.SOM_L3,
    department: DEPT_IDS.MET,
    status: 'draft', // Draft course
    primaryInstructors: [STAFF_IDS.WILLIAM],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.WILLIAM,
  },

  // ============ DBT Courses ============
  {
    _id: COURSE_IDS.DBT_C1,
    title: 'Mock Mindfulness Skills',
    shortDescription: 'Core mindfulness in DBT',
    longDescription: 'The what and how skills of DBT mindfulness practice.',
    program: PROGRAM_IDS.DBT,
    programLevel: LEVEL_IDS.DBT_L1,
    department: DEPT_IDS.MCS,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.JANE,
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.JANE,
  },
  {
    _id: COURSE_IDS.DBT_C2,
    title: 'Mock Wise Mind',
    shortDescription: 'Integrating emotion and reason',
    longDescription: 'Understanding and accessing wise mind in DBT practice.',
    program: PROGRAM_IDS.DBT,
    programLevel: LEVEL_IDS.DBT_L1,
    department: DEPT_IDS.MCS,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.JANE,
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [STAFF_IDS.WILLIAM],
    createdBy: STAFF_IDS.JANE,
  },
  {
    _id: COURSE_IDS.DBT_C3,
    title: 'Mock Crisis Survival',
    shortDescription: 'TIPP and other crisis skills',
    longDescription: 'Distress tolerance skills for crisis situations.',
    program: PROGRAM_IDS.DBT,
    programLevel: LEVEL_IDS.DBT_L2,
    department: DEPT_IDS.MCS,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.JANE,
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.JANE,
  },
  {
    _id: COURSE_IDS.DBT_C4,
    title: 'Mock Radical Acceptance',
    shortDescription: 'Accepting reality as it is',
    longDescription: 'Teaching and practicing radical acceptance with clients.',
    program: PROGRAM_IDS.DBT,
    programLevel: LEVEL_IDS.DBT_L2,
    department: DEPT_IDS.MCS,
    status: 'published',
    publishedAt: now,
    publishedBy: STAFF_IDS.JANE,
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.JANE,
  },
  {
    _id: COURSE_IDS.DBT_C5,
    title: 'Mock DBT Group Skills',
    shortDescription: 'Running DBT skills groups',
    longDescription: 'Structure and facilitation of DBT skills training groups.',
    program: PROGRAM_IDS.DBT,
    programLevel: LEVEL_IDS.DBT_L2,
    department: DEPT_IDS.MCS,
    status: 'draft', // Draft course
    primaryInstructors: [STAFF_IDS.JANE],
    secondaryInstructors: [],
    createdBy: STAFF_IDS.JANE,
  },
];

// Map of courses to their levels for updating programLevel.courses
export const courseLevelMapping = [
  { level: LEVEL_IDS.EXP_L1, courses: [COURSE_IDS.EXP_C1, COURSE_IDS.EXP_C2] },
  { level: LEVEL_IDS.EXP_L2, courses: [COURSE_IDS.EXP_C3, COURSE_IDS.EXP_C4, COURSE_IDS.EXP_C5] },
  { level: LEVEL_IDS.CBT_L1, courses: [COURSE_IDS.CBT_C1, COURSE_IDS.CBT_C2] },
  { level: LEVEL_IDS.CBT_L2, courses: [COURSE_IDS.CBT_C3] },
  { level: LEVEL_IDS.CBT_L3, courses: [COURSE_IDS.CBT_C4, COURSE_IDS.CBT_C5] },
  { level: LEVEL_IDS.EMDR_L1, courses: [COURSE_IDS.EMDR_C1, COURSE_IDS.EMDR_C2] },
  { level: LEVEL_IDS.EMDR_L2, courses: [COURSE_IDS.EMDR_C3, COURSE_IDS.EMDR_C4, COURSE_IDS.EMDR_C5] },
  { level: LEVEL_IDS.SOM_L1, courses: [COURSE_IDS.SOM_C1, COURSE_IDS.SOM_C2] },
  { level: LEVEL_IDS.SOM_L2, courses: [COURSE_IDS.SOM_C3] },
  { level: LEVEL_IDS.SOM_L3, courses: [COURSE_IDS.SOM_C4, COURSE_IDS.SOM_C5] },
  { level: LEVEL_IDS.DBT_L1, courses: [COURSE_IDS.DBT_C1, COURSE_IDS.DBT_C2] },
  { level: LEVEL_IDS.DBT_L2, courses: [COURSE_IDS.DBT_C3, COURSE_IDS.DBT_C4, COURSE_IDS.DBT_C5] },
];
